import type { BulletinRenderData } from './render-data';

// Illustrative-only fixture — used by the template editor's live preview
// AND by the server-side template PDF export (app/print/bulletin-template-preview)
// so a template author can see/export a realistic-looking bulletin without
// needing real class data. The Viewer builds the real BulletinRenderData
// shape from actual grades/appreciations for whichever student is being
// viewed — this fixture never reaches a real bulletin.
export const SAMPLE_BULLETIN_DATA: BulletinRenderData = {
  schoolName: 'École LesÉtoiles',
  schoolLogoUrl: null,
  directorSignatureUrl: null,
  period: 'Trimestre 2',
  academicYear: '2024–2025',
  studentName: 'Jean-Pierre M.',
  className: '3ème A',
  classSize: 28,
  studentNumber: 'N° 2024-0047',
  subjects: [
    {
      name: 'Mathématiques',
      coefficient: 4,
      average: 15.67,
      classAverage: 12.8,
      min: 6.5,
      max: 19.0,
      appreciation: 'Très bon trimestre',
    },
    {
      name: 'Français',
      coefficient: 4,
      average: 12.0,
      classAverage: 11.4,
      min: 5.0,
      max: 17.5,
      appreciation: 'Peut mieux faire',
    },
    {
      name: 'Sciences',
      coefficient: 3,
      average: 18.0,
      classAverage: 13.2,
      min: 8.0,
      max: 20.0,
      appreciation: 'Excellent travail',
    },
    {
      name: 'Anglais',
      coefficient: 3,
      average: 10.0,
      classAverage: 12.1,
      min: 4.5,
      max: 18.0,
      appreciation: 'Efforts nécessaires',
    },
    {
      name: 'Histoire-Géo',
      coefficient: 2,
      average: 16.5,
      classAverage: 11.9,
      min: 7.0,
      max: 19.5,
      appreciation: 'Très bonne maîtrise',
    },
  ],
  overallAverage: 14.38,
  classAverage: 12.5,
  rank: 4,
  rankedCount: 28,
  generalAppreciation:
    "Élève sérieux et investi qui fait preuve d'une bonne volonté dans l'ensemble des matières. Les résultats en sciences sont excellents et encourageants. Des efforts supplémentaires sont attendus en anglais pour consolider les acquis. Continuez ainsi !",
  absencesDays: 3,
  retards: 1,
  firstName: 'Jean-Pierre',
  lastName: 'M.',
  schoolAddress: '12 Rue des Écoles, Port-au-Prince',
  schoolPhone: '+509 1234 5678',
  schoolEmail: 'contact@lesetoiles.edu.ht',
  termLabel: 'Trimestre 2',
  academicYearLabel: '2024–2025',
  qualitativeSubjects: [
    {
      subjectName: 'Comportement',
      ratingScale: ['Toujours', 'Souvent', 'Parfois', 'Jamais'],
      criteria: [
        { label: 'Respecte les consignes', level: 0 },
        { label: "Participe à l'oral", level: 1 },
        { label: 'Respecte ses camarades', level: 0 },
        { label: 'Range son matériel', level: 2 },
        { label: 'Fait preuve de politesse', level: 0 },
      ],
    },
    {
      subjectName: 'Développement physique',
      ratingScale: ['Excellent', 'Très bien', 'Bien', 'Assez bien'],
      criteria: [
        { label: 'Motricité globale', level: 1 },
        { label: 'Motricité fine', level: 0 },
        { label: 'Coordination', level: 1 },
        { label: 'Autonomie corporelle', level: 2 },
        { label: 'Endurance', level: 1 },
      ],
    },
  ],
  nisu: '0123456789',
  year: {
    terms: [
      {
        termId: 'c1',
        label: '1er contrôle',
        order: 1,
        hasGrades: true,
        subjects: [
          { subjectName: 'Mathématiques', domain: 'Sciences', points: 62.7, maxPoints: 80 },
          { subjectName: 'Sciences', domain: 'Sciences', points: 54, maxPoints: 60 },
          { subjectName: 'Français', domain: 'Lettres', points: 48, maxPoints: 80 },
          { subjectName: 'Anglais', domain: 'Lettres', points: 30, maxPoints: 60 },
          { subjectName: 'Histoire-Géo', domain: null, points: 33, maxPoints: 40 },
        ],
        totalPoints: 227.7,
        totalMax: 320,
        average10: 7.1,
        rank: 4,
        rankedCount: 28,
        coefficientSum: 16,
      },
      {
        termId: 'c2',
        label: '2ème contrôle',
        order: 2,
        hasGrades: true,
        subjects: [
          { subjectName: 'Mathématiques', domain: 'Sciences', points: 58, maxPoints: 80 },
          { subjectName: 'Sciences', domain: 'Sciences', points: 51, maxPoints: 60 },
          { subjectName: 'Français', domain: 'Lettres', points: 52, maxPoints: 80 },
          { subjectName: 'Anglais', domain: 'Lettres', points: null, maxPoints: 60 },
          { subjectName: 'Histoire-Géo', domain: null, points: 30, maxPoints: 40 },
        ],
        totalPoints: 191,
        totalMax: 320,
        average10: 6,
        rank: 6,
        rankedCount: 28,
        coefficientSum: 16,
      },
      {
        termId: 'c3',
        label: '3ème contrôle',
        order: 3,
        hasGrades: false,
        subjects: [
          { subjectName: 'Mathématiques', domain: 'Sciences', points: null, maxPoints: 80 },
          { subjectName: 'Sciences', domain: 'Sciences', points: null, maxPoints: 60 },
          { subjectName: 'Français', domain: 'Lettres', points: null, maxPoints: 80 },
          { subjectName: 'Anglais', domain: 'Lettres', points: null, maxPoints: 60 },
          { subjectName: 'Histoire-Géo', domain: null, points: null, maxPoints: 40 },
        ],
        totalPoints: null,
        totalMax: 320,
        average10: null,
        rank: null,
        rankedCount: 0,
        coefficientSum: 16,
      },
      {
        termId: 'c4',
        label: '4ème contrôle',
        order: 4,
        hasGrades: false,
        subjects: [
          { subjectName: 'Mathématiques', domain: 'Sciences', points: null, maxPoints: 80 },
          { subjectName: 'Sciences', domain: 'Sciences', points: null, maxPoints: 60 },
          { subjectName: 'Français', domain: 'Lettres', points: null, maxPoints: 80 },
          { subjectName: 'Anglais', domain: 'Lettres', points: null, maxPoints: 60 },
          { subjectName: 'Histoire-Géo', domain: null, points: null, maxPoints: 40 },
        ],
        totalPoints: null,
        totalMax: 320,
        average10: null,
        rank: null,
        rankedCount: 0,
        coefficientSum: 16,
      },
    ],
    generalAverage: 13.1,
    generalCoefficient: 32,
  },
};
