// Monolith: the API lives in the same Next.js app under /api/*, so the
// default is an empty string (same-origin / relative fetch). Override only
// for rare cross-origin setups (e.g. a mobile client hitting a hosted
// instance). The legacy `http://localhost:4000` default was a leftover from
// the pre-monolith era when the backend ran as a separate Express server.
export const API_URL = process.env.NEXT_PUBLIC_API_URL ?? '';
export const COOKIE_PREFIX = process.env.NEXT_PUBLIC_COOKIE_PREFIX ?? 'app';

// French copy for the login screen — see .planning/banani/login-page.md.
export const AUTH_LOGIN = {
  headline: 'Gérez votre école, simplement.',
  subline:
    'La plateforme tout-en-un pour les établissements scolaires : notes, présences, bulletins et bien plus.',
  features: [
    'Saisie et gestion des notes par matière',
    'Suivi des présences en temps réel',
    'Génération automatique des bulletins',
    'Statistiques et rapports détaillés',
  ],
  welcome: 'Bienvenue 👋',
  formSubtitle:
    'Connectez-vous à votre espace pour accéder au tableau de bord de votre établissement.',
  roleTabs: {
    admin: 'Administrateur',
    teacher: 'Enseignant',
    studentParent: 'Élève / Parent',
  },
  emailLabel: 'Adresse e-mail',
  passwordLabel: 'Mot de passe',
  forgotPassword: 'Mot de passe oublié ?',
  rememberMe: 'Se souvenir de moi sur cet appareil',
  submit: 'Se connecter',
  submitting: 'Connexion…',
  noAccount: 'Pas encore de compte ?',
  contactAdmin: "Contacter l'administrateur",
  securityNote: 'Connexion sécurisée — vos données sont chiffrées',
  errors: {
    TOO_MANY_LOGIN_ATTEMPTS: 'Trop de tentatives. Réessaie dans quelques minutes.',
    default: 'E-mail ou mot de passe incorrect.',
    network: 'Erreur réseau. Réessaie.',
  },
} as const;

// French copy for the "Mot de passe oublié" screen.
export const AUTH_FORGOT_PASSWORD = {
  title: 'Mot de passe oublié ?',
  subtitle: 'Indique ton adresse e-mail — on t’envoie un code pour réinitialiser ton mot de passe.',
  emailLabel: 'Adresse e-mail',
  submit: 'Envoyer le code',
  submitting: 'Envoi…',
  backToLogin: 'Retour à la connexion',
  confirmation: {
    title: 'Vérifie ta boîte mail',
    body: (email: string) =>
      `Si un compte existe pour ${email}, un code de réinitialisation vient d'être envoyé — il expire dans 15 minutes.`,
  },
  errors: {
    TOO_MANY_FORGOT_ATTEMPTS: 'Trop de demandes pour cette adresse. Réessaie dans une heure.',
    default: 'Une erreur est survenue. Réessaie.',
    network: 'Erreur réseau. Réessaie.',
  },
} as const;

// French copy for the /reset-password screen — consumes a PASSWORD_RESET
// code sent by /forgot-password. Does not log the user in (the API route
// deliberately issues no cookies) — success sends them back to /login.
export const AUTH_RESET_PASSWORD = {
  title: 'Réinitialise ton mot de passe',
  subtitle: 'Entre le code reçu par email et choisis un nouveau mot de passe.',
  emailLabel: 'Adresse e-mail',
  codeLabel: 'Code de réinitialisation',
  codePlaceholder: 'XXXXXXXX',
  passwordLabel: 'Nouveau mot de passe',
  submit: 'Réinitialiser le mot de passe',
  submitting: 'Réinitialisation…',
  backToLogin: 'Retour à la connexion',
  done: {
    title: 'Mot de passe mis à jour 🎉',
    subtitle: 'Tu peux maintenant te connecter avec ton nouveau mot de passe.',
    cta: 'Se connecter',
  },
  errors: {
    VERIFICATION_CODE_INVALID: 'Code invalide. Vérifie ta saisie.',
    VERIFICATION_CODE_EXPIRED: 'Ce code a expiré — demande-en un nouveau.',
    TOO_MANY_RESET_ATTEMPTS: 'Trop de tentatives. Réessaie dans quelques minutes.',
    PASSWORD_BANNED: 'Ce mot de passe est trop courant — choisis-en un autre.',
    PASSWORD_TOO_SHORT: 'Mot de passe trop court.',
    PASSWORD_PWNED: 'Ce mot de passe est apparu dans une fuite de données connue.',
    default: 'Une erreur est survenue. Réessaie.',
    network: 'Erreur réseau. Réessaie.',
  },
} as const;

// French copy for the "Créer une école" admin modal — see
// .planning/banani/create-school.md. Was a dedicated page, now a Modal
// opened from /admin and /admin/schools (no more navigation away).
export const ADMIN_CREATE_SCHOOL = {
  title: 'Créer une nouvelle école',
  subtitle: "Renseignez les informations de l'établissement",
  schoolSection: {
    title: "Informations de l'établissement",
    subtitle: "Nom, localisation et type d'école",
    logo: "Logo de l'école",
    logoHint: 'PNG, JPG ou WebP — affiché dans les entêtes et bulletins',
    schoolName: "Nom de l'école",
    shortName: 'Nom abrégé / Sigle',
    shortNameHint: 'Utilisé pour les avatars et badges de l’école',
    country: 'Pays',
    city: 'Ville',
    schoolType: "Type d'établissement",
    primaryLanguage: 'Langue principale',
    address: 'Adresse complète',
    addressPlaceholder: 'Ex : 12, Rue des Mangues, Pétion-Ville',
    phone: 'Téléphone',
    phonePlaceholder: '+509...',
    estimatedStudents: "Nombre d'élèves estimé",
    estimatedStudentsHint: 'Utilisé pour estimer le coût mensuel',
  },
  adminSection: {
    title: 'Administrateur responsable',
    subtitle: 'Compte principal qui recevra les identifiants',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Adresse e-mail',
    emailHint: 'Un email de vérification sera envoyé à cette adresse pour activer le compte',
    role: 'Rôle',
    phone: 'Téléphone',
  },
  schoolTypes: [
    'École primaire',
    'École secondaire',
    'École primaire & secondaire',
    'Université',
    'Autre',
  ],
  cancel: 'Annuler',
  submit: 'Créer l’école',
  submitting: 'Création…',
  requiredFieldsError: 'Merci de remplir tous les champs obligatoires.',
  successTitle: 'École créée avec succès',
  newAccountCreated: 'Un nouveau compte a été créé pour le propriétaire de cette école.',
  existingAccountLinked: 'Le compte existant a été ajouté comme propriétaire de cette école.',
  verificationEmailSentLabel: 'Email de vérification envoyé',
  verificationEmailSentNote:
    'Le propriétaire doit saisir le code reçu par email sur la page de vérification pour activer son compte et définir son propre mot de passe.',
  close: 'Fermer',
} as const;

// Statut catalog for the Établissement settings tab's "Type d'établissement"
// field — distinct from ADMIN_CREATE_SCHOOL.schoolTypes, which models
// teaching *levels* (relabeled "Niveaux d'enseignement" on this same tab).
export const SCHOOL_STATUTES = [
  'École publique',
  'École privée laïque',
  'École privée confessionnelle',
  'École communautaire',
  'École internationale',
  'Autre',
] as const;

// "Type de période" catalog for the Nouvelle période modal — Term.type.
export const TERM_TYPES = [
  { value: 'TRIMESTRE', label: 'Trimestre', sub: '3 par an', icon: 'calendar' },
  { value: 'SEMESTRE', label: 'Semestre', sub: '2 par an', icon: 'calendar-range' },
  { value: 'LIBRE', label: 'Période libre', sub: 'Personnalisée', icon: 'layers' },
] as const;

// French ordinal labels for the "Numéro de la période" picker — purely a
// default-label helper on the client (see AnneeScolaireTab), the server
// still auto-assigns Term.order sequentially.
export const ORDINAL_LABELS = ['1er', '2e', '3e', '4e', '5e', '6e', '7e', '8e'] as const;

// French copy for the /verify-email screen — consumes an EMAIL_VERIFY code
// (signup, or a school owner invited via the admin's "Créer une école" flow), logs the user
// in, then offers a one-time "set your password" step for accounts created
// without one (owners invited by an admin).
export const AUTH_VERIFY_EMAIL = {
  title: 'Vérifie ton adresse e-mail',
  subtitle: 'Entre le code à 8 caractères reçu par email pour activer ton compte.',
  emailLabel: 'Adresse e-mail',
  codeLabel: 'Code de vérification',
  codePlaceholder: 'XXXXXXXX',
  submit: 'Vérifier',
  submitting: 'Vérification…',
  backToLogin: 'Retour à la connexion',
  setPassword: {
    title: 'Adresse vérifiée 🎉',
    subtitle: 'Choisis un mot de passe pour te connecter la prochaine fois.',
    passwordLabel: 'Nouveau mot de passe',
    submit: 'Définir le mot de passe',
    submitting: 'Enregistrement…',
    skip: 'Plus tard',
  },
  done: {
    title: 'Tout est prêt !',
    cta: 'Accéder au tableau de bord',
  },
  errors: {
    VERIFICATION_CODE_INVALID: 'Code invalide. Vérifie ta saisie.',
    VERIFICATION_CODE_EXPIRED: 'Ce code a expiré — demande-en un nouveau.',
    TOO_MANY_VERIFY_ATTEMPTS: 'Trop de tentatives. Réessaie dans quelques minutes.',
    default: 'Une erreur est survenue. Réessaie.',
    network: 'Erreur réseau. Réessaie.',
  },
} as const;

// French copy for Frais & Scolarité (Payment Configuration / Fee Management
// / Relances Impayés / Payment Registration) — see
// .planning/banani/frais-scolarite.md.
export const FEES = {
  currency: 'HTG',
  nav: { label: 'Frais & Scolarité' },
  tabs: {
    paiements: 'Suivi des paiements',
    relances: 'Relances & Impayés',
    configuration: 'Configuration',
  },
  studentStatusLabel: {
    UP_TO_DATE: 'À jour',
    PARTIAL: 'Partiel',
    OVERDUE: 'En retard',
    UNPAID: 'Non payé',
  },
  trancheStatusLabel: {
    PAID: 'Payée',
    PARTIAL: 'Partiel',
    OVERDUE: 'En retard',
    UPCOMING: 'À venir',
  },
  paymentMethodLabel: {
    ESPECES: 'Espèces',
    MONCASH: 'MonCash',
    NATCASH: 'Natcash',
    CHEQUE: 'Chèque',
    VIREMENT: 'Virement',
  },
  configuration: {
    title: "Configuration des Frais d'Études",
    subtitle:
      "Définissez les frais de scolarité et les tranches par classe pour l'année académique",
    classListTitle: 'Classes de l’école',
    classListSubtitle: 'Sélectionnez une classe à configurer',
    configuredCount: (done: number, total: number) => `Configurées ${done} / ${total}`,
    filterAll: 'Toutes',
    filterConfigured: 'Configurées',
    filterPending: 'En attente',
    classSearchPlaceholder: 'Filtrer les classes...',
    globalSettingsTitle: 'Paramètres globaux',
    latePenaltyToggle: 'Pénalités de retard',
    latePenaltyToggleDesc: 'Appliquer des frais après la date limite',
    autoRemindersToggle: 'Rappels automatiques',
    autoRemindersToggleDesc: 'Notifications avant l’échéance',
    currencyLabel: 'Devise principale',
    currencyOptions: [
      { code: 'HTG', label: 'HTG — Gourde haïtienne' },
      { code: 'USD', label: 'USD — Dollar américain' },
      { code: 'XOF', label: 'XOF — Franc CFA (UEMOA)' },
      { code: 'XAF', label: 'XAF — Franc CFA (CEMAC)' },
      { code: 'EUR', label: 'EUR — Euro' },
    ],
    editorConfigured: 'Configuré',
    editorPending: 'En attente',
    editorSubtitle: 'Définissez le montant total et les tranches pour cette classe',
    copyFromClass: 'Copier depuis une classe',
    save: 'Enregistrer',
    generalInfoTitle: 'Informations générales',
    totalAmountLabel: 'Montant total annuel',
    registrationFeeLabel: "Frais d'inscription",
    academicYearLabel: 'Année académique',
    tranchesBuilderTitle: 'Configurateur de Tranches',
    tranchesBuilderSubtitle: (total: string, count: number) =>
      `Total réparti : ${total} sur ${count} versements`,
    distributionLabel: (pct: number) => `Répartition : ${pct}%`,
    distributionPrefix: 'Répartition :',
    addTranche: 'Ajouter une tranche',
    editTranche: 'Modifier la tranche',
    trancheLabelField: 'Libellé',
    trancheDueDateField: 'Date limite',
    trancheAmountField: 'Montant / Pourcentage',
    trancheLatePenaltyField: 'Pénalité de retard (optionnel)',
    trancheGraceDaysField: 'Délai de grâce (jours)',
    noLatePenalty: 'Aucune pénalité',
    trancheLatePenaltySummary: (percent: number, graceDays: number | null) =>
      graceDays != null ? `${percent}% après ${graceDays} j.` : `${percent}%`,
    saveTranche: 'Enregistrer',
    saveBarHelper: 'Les modifications ne seront appliquées qu’après enregistrement.',
    cancel: 'Annuler',
    saveConfiguration: 'Enregistrer la configuration',
    emptyClassPrompt: 'Aucune configuration — définissez le montant total pour commencer.',
    noClassFound: 'Aucune classe trouvée.',
    selectClassPrompt: 'Sélectionnez une classe.',
  },
  overview: {
    title: 'Gestion des Frais & Scolarité',
    subtitle: 'Suivi des paiements, tranches et relances',
    export: 'Exporter',
    configureFees: 'Paramétrage des plans',
    yearFilterAll: 'Année :',
    trancheFilterAll: 'Toutes les tranches',
    alertBanner: (count: number, tranche: string, dueDate: string) =>
      `${count} élèves en retard de paiement — ${tranche} échue le ${dueDate}`,
    alertBannerSub: (amount: string) => `Montant total impayé : ${amount}`,
    kpiTotalCollected: 'Total Recouvré',
    kpiUpToDate: 'Élèves à jour',
    kpiOverdue: 'En Retard',
    kpiNextDueDate: 'Prochaine Échéance',
    searchPlaceholder: 'Nom ou matricule...',
    classFilterAll: 'Toutes les classes',
    statusFilterAll: 'Tous les statuts',
    resultCount: (n: number) => `${n} élèves`,
    columns: {
      student: 'Élève',
      class: 'Classe',
      totalDue: 'Total dû',
      paid: 'Payé',
      remaining: 'Reste à payer',
      status: 'Statut',
      tranches: 'Tranches',
      actions: 'Actions',
    },
    rowActions: {
      registerPayment: 'Enregistrer un paiement',
      sendWhatsapp: 'Envoyer WhatsApp',
      viewHistory: "Voir l'historique",
      printReceipt: 'Imprimer le reçu',
    },
  },
  overdue: {
    title: 'Relances & Impayés',
    subtitle: 'Gérez les retards de paiement et automatisez les rappels',
    exportList: 'Exporter la liste',
    bulkReminder: (count: number) => (count > 0 ? `Rappel groupé (${count})` : 'Rappel groupé'),
    kpiTotalUnpaid: 'Total impayés',
    kpiCritical: 'Retard critique',
    kpiSent: 'Rappels envoyés',
    kpiNextDue: 'Prochaine échéance',
    searchPlaceholder: 'Nom ou matricule...',
    trancheFilterAll: 'Toutes les tranches',
    statusFilterOverdue: 'En retard',
    selectedCount: (n: number) => `${n} sélectionnés`,
    sendReminder: 'Envoyer rappel',
    columns: {
      student: 'Élève',
      class: 'Classe',
      tranche: 'Tranche',
      amountDue: 'Montant dû',
      overdue: 'Retard',
      status: 'Statut',
      lastReminder: 'Dernier rappel',
      actions: 'Actions',
    },
    daysOverdue: (n: number) => `${n} jours`,
    statusCritical: 'Critique',
    statusOverdue: 'En retard',
    statusRecent: 'Récent',
    rowActions: {
      registerPayment: 'Enregistrer un paiement',
      sendReminder: 'Envoyer rappel WhatsApp',
      viewHistory: "Voir l'historique",
      markDisputed: 'Marquer comme litigieux',
    },
    automationTitle: 'Automatisation',
    automationSubtitle: 'Rappels automatiques',
    reminderBefore5Days: 'Rappel 5 jours avant',
    reminderBefore5DaysDesc: "Notifier avant l'échéance",
    reminderOnDueDate: 'Rappel le jour J',
    reminderOnDueDateDesc: "Le jour de l'échéance",
    reminderWeekly: 'Rappel hebdomadaire',
    reminderWeeklyDesc: 'Pour les impayés > 7 jours',
    reminderCritical: 'Alerte critique',
    reminderCriticalDesc: 'Retard > 30 jours',
    byClassTitle: 'Retards par classe',
    quickActionsTitle: 'Actions rapides',
    exportExcel: 'Exporter Excel',
  },
  registerPayment: {
    title: 'Enregistrer un paiement',
    subtitle: 'Saisissez les informations du versement ci-dessous',
    balanceLabel: 'Solde dû',
    selectTranche: 'Sélectionner la tranche',
    latePenaltyNote: (amount: string, percent: number) =>
      `Une pénalité de retard de ${amount} (${percent}%) sera appliquée automatiquement sur cette tranche.`,
    detailsTitle: 'Détails du versement',
    amountLabel: 'Montant versé',
    dateLabel: 'Date du paiement',
    referenceLabel: 'N° Référence / Reçu',
    referencePlaceholder: 'REF-2026-...',
    notesLabel: 'Notes (optionnel)',
    notesPlaceholder: 'Remarques...',
    methodTitle: 'Mode de paiement',
    totalTitle: 'Montant total à encaisser',
    breakdownLabel: (principal: string, penalty: string) =>
      `Principal ${principal} + Pénalité ${penalty}`,
    remainingAfter: 'Solde restant après paiement',
    settled: 'Compte soldé',
    cancel: 'Annuler',
    saveAndPrint: 'Enregistrer & Imprimer le reçu',
    confirm: 'Confirmer le paiement',
  },
  disputeModal: {
    title: 'Marquer comme litigieux',
    reasonLabel: 'Motif (optionnel)',
    confirm: 'Marquer comme litigieux',
    cancel: 'Annuler',
  },
  stub: 'Cette fonctionnalité arrive bientôt.',
} as const;

// ─── School Dashboard (Epic 3 — .planning/banani/school-dashboard.md) ───
export const DASHBOARD = {
  title: 'Tableau de bord',
  subtitle: (name: string) => `Bienvenue, ${name} — voici l'aperçu de l'établissement`,
  export: 'Export',
  kpis: {
    students: 'Élèves inscrits',
    teachers: 'Enseignants',
    classes: 'Classes actives',
    subjects: 'Matières',
    attendanceRate: 'Taux de présence',
    attendanceRateSub: 'Cette semaine',
    thisMonth: 'ce mois',
  },
  averagesTrend: {
    title: 'Évolution des moyennes',
    subtitle: (yearLabel: string) => `Année scolaire ${yearLabel}`,
    seriesLabel: 'Moyenne générale',
  },
  levelDistribution: {
    title: 'Répartition par niveau',
    subtitle: 'Élèves inscrits',
    centerLabel: 'élèves',
  },
  fees: {
    title: 'Suivi des frais de scolarité',
    seeDetails: 'Voir les détails →',
    collected: 'Total Recouvré',
    collectedLabel: 'collecté',
    paid: 'Payé',
    remaining: 'Restant',
    overdueStudents: 'Élèves en Retard',
    overdueLabel: 'en retard',
    upToDate: 'À jour',
    studentsConcerned: (n: number) => `${n} élève${n > 1 ? 's' : ''} concerné${n > 1 ? 's' : ''}`,
    nextDue: 'Prochaine Échéance',
    daysUntil: (n: number) => (n <= 0 ? "Aujourd'hui" : n === 1 ? 'Demain' : `Dans ${n} jours`),
    trancheProgress: 'Avancement des tranches',
    noFeeData: 'Aucune structure de frais configurée pour le moment.',
  },
  attendanceByClass: {
    title: 'Taux de présence',
    subtitle: 'Par classe — ce mois',
    details: 'Détails →',
  },
  subjectPerformance: {
    title: 'Performance par matière',
    subtitle: 'Moyenne générale toutes classes',
  },
  todos: {
    title: 'À traiter',
    evaluationsToGrade: 'Évaluations à corriger',
    evaluationsOverdueLabel: (n: number) => `${n} en retard`,
    unjustifiedAbsences: 'Absences non justifiées',
    unjustifiedAbsencesSub: 'Cette semaine',
    teachersWithoutClass: 'Enseignants sans classe assignée',
    teachersWithoutClassSub: 'À affecter',
    overduePayments: 'Paiements en retard',
    overduePaymentsSub: 'Relances à envoyer',
  },
  activity: {
    title: 'Activité récente',
    seeAll: 'Tout voir',
    empty: 'Aucune activité récente.',
    gradeUpdated: (subject: string, className: string) =>
      `Notes de ${subject} (${className}) mises à jour`,
    absenceMarked: (name: string, className: string) => `${name} marqué(e) absent — ${className}`,
    paymentRecorded: (name: string, className: string) =>
      `Paiement enregistré — ${name} (${className})`,
    studentEnrolled: (name: string, className: string) => `${name} ajouté(e) en ${className}`,
  },
  activityLog: {
    title: "Journal d'activité",
    subtitle: "Historique complet des évènements de l'établissement",
    back: 'Retour au tableau de bord',
    filterAll: 'Tous les types',
    typeLabel: {
      grade: 'Notes',
      absence: 'Absences',
      payment: 'Paiements',
      enrollment: 'Inscriptions',
    },
    empty: 'Aucune activité pour le moment.',
    resultCount: (n: number) => `${n} évènement${n > 1 ? 's' : ''}`,
  },
  emptyYear:
    "Aucune année scolaire active — configure d'abord l'année scolaire dans « Paramètres ».",
} as const;

// ─── Academic Year Rollover (Passage à l'année scolaire suivante) ───
export const ACADEMIC_YEAR_ROLLOVER = {
  title: "Passage à l'année scolaire suivante",
  subtitle: (oldYear: string, newYear: string) => `Migration de ${oldYear} vers ${newYear}`,
  warningBanner: 'Cette action ne peut pas être annulée',
  irreversible: 'Impossible à annuler',

  step1: {
    title: 'Nouvelle année',
    yearLabel: 'Année scolaire',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    saveAsDraft: 'Sauvegarder le brouillon',
    nextStep: 'Étape suivante',
    validation: {
      yearRequired: "L'année scolaire est requise",
      startDateRequired: 'La date de début est requise',
      endDateRequired: 'La date de fin est requise',
      endDateAfterStart: 'La date de fin doit être après la date de début',
    },
  },

  step2: {
    title: 'Promotion des élèves',
    currentClass: 'Classe actuelle',
    studentCount: 'Élèves',
    currentLevel: 'Niveau actuel',
    destClass: 'Classe de destination',
    help: "Choisis, pour chaque classe actuelle, la classe de destination parmi les classes de l'école (elle sera recréée dans la nouvelle année avec les mêmes réglages), ou marque-la « Fin de cursus » si ses élèves quittent l'établissement.",
    pickDestination: '— Choisir une classe —',
    endOfCursus: 'Fin de cursus — non réinscrits',
    legacyNewClass: (name: string) => `Nouvelle classe « ${name} » (brouillon précédent)`,
    demotionHint: (name: string, level: string) =>
      `Rétrogradation impossible vers ${name} (${level}) — choisis un niveau égal ou supérieur.`,
    suggestAll: 'Suggérer toutes les promotions',
    suggestHint:
      "Configure l'ordre des niveaux dans Configuration > Niveaux pour activer les suggestions automatiques.",
    suggestApplied: (n: number) =>
      n === 1
        ? '1 classe pré-remplie — vérifie et ajuste si besoin.'
        : `${n} classes pré-remplies — vérifie et ajuste si besoin.`,
    suggestNone:
      "Aucune classe à pré-remplir : toutes sont déjà décidées, ou leur niveau n'est pas dans le catalogue, ou aucune classe existante ne correspond au niveau suivant.",
    step3Preview: "Aperçu — Étape 3 (Disponible après validation de l'étape 2)",
    previousStep: 'Étape précédente',
    nextStep: 'Étape suivante — Décisions par élève',
    // « classe par classe » — user decision 2026-08-17: for a school with
    // many classes, deciding all of them in one big table can take a long
    // time; offer a focused one-class-at-a-time flow as an alternative.
    viewTable: 'Tableau',
    viewPerClass: 'Classe par classe',
    goToClass: 'Aller à une classe',
    classProgress: (current: number, total: number) => `Classe ${current} sur ${total}`,
    decidedCount: (n: number, total: number) =>
      `${n} classe${n > 1 ? 's' : ''} décidée${n > 1 ? 's' : ''} sur ${total}`,
    decidedBadge: 'Décidée',
    prevClass: 'Classe précédente',
    nextClass: 'Classe suivante',
  },

  step3: {
    title: 'Décisions par élève',
    help: 'Par défaut, chaque élève suit la destination de sa classe (étape 2). Indique ici les cas particuliers : redoublement, autre classe, ou élève qui ne se réinscrit pas.',
    searchPlaceholder: 'Rechercher un élève...',
    allClasses: 'Toutes les classes',
    student: 'Élève',
    currentClass: 'Classe actuelle',
    decision: 'Décision',
    destination: 'Destination',
    followClass: (dest: string) => `Comme la classe → ${dest}`,
    followClassUnenrolled: 'Comme la classe → non réinscrit',
    repeat: (currentClass: string) => `Redouble → ${currentClass}`,
    leave: 'Non réinscrit',
    otherClass: (name: string, level: string) => `Autre classe → ${name} (${level})`,
    noDestination: '—',
    unenrolled: 'Non réinscrit',
    summary: (total: number, promoted: number, repeating: number, unenrolled: number) =>
      `${total} élève${total > 1 ? 's' : ''} · ${promoted} passe${promoted > 1 ? 'nt' : ''} · ${repeating} redouble${repeating > 1 ? 'nt' : ''} · ${unenrolled} non réinscrit${unenrolled > 1 ? 's' : ''}`,
    noResults: 'Aucun élève ne correspond à la recherche.',
    noStudents: "Aucun élève inscrit dans l'année en cours.",
    demotionHint: (name: string, level: string) =>
      `Rétrogradation impossible vers ${name} (${level}) — choisis un niveau égal ou supérieur.`,
    previousStep: 'Étape précédente',
    saveAsDraft: 'Sauvegarder le brouillon',
    nextStep: 'Étape suivante — Récapitulatif',
  },

  step4: {
    title: 'Récapitulatif',
    promoted: 'Élèves promus',
    repeating: 'Redoublants',
    unenrolled: 'Non réinscrits',
    students: 'Élèves',
    allStudents: (count: number) => `Voir tous les élèves (${count}) →`,
    confirmTitle: "Confirmer le passage à l'année suivante",
    confirmText: (
      oldYear: string,
      newYear: string,
      promotedCount: number,
      repeatingCount: number,
    ) =>
      `La confirmation créera l'année scolaire ${newYear}, promouvra ${promotedCount} élève${promotedCount > 1 ? 's' : ''}${repeatingCount > 0 ? ` (${repeatingCount} redoublant${repeatingCount > 1 ? 's' : ''})` : ''} et archivera l'année ${oldYear}. Cette action ne peut pas être annulée.`,
    typeToConfirm: 'Tapez le nom de votre école pour confirmer',
    confirmButton: 'Confirmer',
    previousStep: 'Étape précédente — Modifier les décisions',
  },

  studentStatus: {
    promoted: 'Promu',
    repeating: 'Redoublant',
    unenrolled: 'Non réinscrit',
  },

  emptyState: "Aucune classe dans l'année en cours — configure d'abord des classes.",
  backToSettings: 'Retour aux paramètres',

  success: (newYear: string) => `Année scolaire ${newYear} créée avec succès`,
  error: 'Une erreur est survenue',
} as const;

// ─── SaaS admin (Epic 2 — .planning/banani/epic-2-admin-foundation.md) ───

// Shared status/plan vocabulary — one label per status app-wide (the Banani
// dashboard mock said "Payé" where the transactions mock said "Réussie";
// we standardize on the transactions vocabulary, deviation noted in plan).
export const ADMIN_SAAS = {
  subscriptionStatus: {
    TRIAL: 'Essai',
    ACTIVE: 'Actif',
    EXPIRED: 'Expiré',
    SUSPENDED: 'Suspendu',
    CANCELED: 'Annulé',
    NONE: 'Inactif',
  },
  expiringSoon: 'Expire bientôt',
  transactionStatus: {
    SUCCEEDED: 'Réussie',
    PENDING: 'En attente',
    FAILED: 'Échouée',
    REFUNDED: 'Remboursée',
  },
  couponStatus: {
    ACTIVE: 'Actif',
    EXPIRING: 'Bientôt expiré',
    EXHAUSTED: 'Épuisé',
    EXPIRED: 'Expiré',
    INACTIVE: 'Désactivé',
  },
  userStatus: { ACTIVE: 'Actif', SUSPENDED: 'Suspendu' },
  orgRole: { OWNER: 'Propriétaire', ADMIN: 'Admin', MEMBER: 'Membre' },
  planEmoji: { ENTERPRISE: '⭐', PRO: '📚', STARTER: '🚀' } as Record<string, string>,
  stub: 'Cette fonctionnalité arrive bientôt.',
} as const;

export const ADMIN_DASHBOARD = {
  title: 'Tableau de bord Administration',
  subtitle: 'Vue globale de la plateforme',
  exportReport: 'Exporter le rapport',
  createSchool: 'Créer une école',
  seeAll: 'Voir tout',
  kpi: {
    totalSchools: 'Écoles actives',
    totalUsers: 'Utilisateurs totaux',
    activeUsers: 'Utilisateurs actifs',
    activeSubscriptions: 'Abonnements actifs',
    monthRevenue: 'Revenus du mois',
    thisMonth: 'ce mois',
    ofTotal: 'du total',
    expiringSoon: 'expirent bientôt',
    vsLastMonth: 'vs mois dernier',
  },
  revenue: {
    title: 'Évolution des revenus',
    subtitle: '6 derniers mois · Facturation par élève',
    total: 'Total 6 mois',
    avg: 'Moy. mensuelle',
    growth: 'Croissance',
  },
  recentUsers: {
    title: 'Utilisateurs récents',
    subtitle: 'Dernières inscriptions',
    empty: 'Aucun utilisateur pour le moment.',
  },
  schools: {
    title: 'Écoles clientes',
    subtitle: (n: number) =>
      `${n} établissement${n > 1 ? 's' : ''} enregistré${n > 1 ? 's' : ''} sur la plateforme`,
    searchPlaceholder: 'Rechercher...',
    newSchool: 'Nouvelle école',
    columns: {
      school: 'École',
      location: 'Pays / Ville',
      plan: 'Plan',
      students: 'Élèves',
      users: 'Utilisateurs',
      billing: 'Facturation / mois',
      status: 'Statut',
      renewal: 'Renouvellement',
    },
    empty: 'Aucune école enregistrée pour le moment.',
  },
  transactions: {
    title: 'Transactions récentes',
    subtitle: 'Historique des paiements',
    columns: { school: 'École', amount: 'Montant', date: 'Date', status: 'Statut' },
    empty: 'Aucune transaction pour le moment.',
  },
  coupons: {
    title: 'Codes promotionnels',
    subtitle: 'Gérez les coupons de réduction',
    newCoupon: 'Nouveau coupon',
    columns: {
      code: 'Code',
      discount: 'Réduction',
      uses: 'Utilisations',
      expiry: 'Expiration',
      status: 'Statut',
    },
    noLimit: 'Sans limite',
    permanent: 'Permanent',
    empty: 'Aucun coupon créé pour le moment.',
  },
  loadError: 'Impossible de charger le tableau de bord.',
  retry: 'Réessayer',
} as const;

export const ADMIN_SCHOOLS = {
  title: 'Écoles clientes',
  subtitle: 'Liste de tous les établissements inscrits sur la plateforme',
  exportCsv: 'Exporter CSV',
  createSchool: 'Créer une école',
  kpi: {
    totalSchools: 'Total écoles',
    activeSubscriptions: 'Abonnements actifs',
    pendingOrSuspended: (n: number) => `${n} en attente / suspension`,
    totalStudents: 'Total élèves',
    monthRevenue: 'Revenu mensuel',
    thisMonth: 'ce mois',
    vsLastMonth: 'vs mois dernier',
  },
  filters: {
    searchPlaceholder: 'Rechercher une école...',
    allPlans: 'Tous les plans',
    allStatuses: 'Tous les statuts',
    allCountries: 'Tous les pays',
    results: (n: number) => `${n} résultat${n > 1 ? 's' : ''}`,
  },
  columns: {
    school: 'École',
    plan: 'Plan',
    status: 'Statut',
    students: 'Élèves',
    revenue: 'Revenu/mois',
    owner: 'Admin responsable',
    createdAt: 'Inscription',
    lastAccess: 'Dernier accès',
    actions: 'Actions',
  },
  actions: {
    viewProfile: 'Voir le profil',
    accessSchool: "Accéder à l'école",
    edit: 'Modifier les infos',
    manageSubscription: "Gérer l'abonnement",
    resetPassword: 'Réinitialiser mdp',
    suspend: 'Suspendre',
    reactivate: 'Réactiver',
    delete: "Supprimer l'école",
  },
  profileModal: {
    title: "Profil de l'école",
    owner: 'Admin responsable',
    location: 'Localisation',
    code: 'Code officiel',
    plan: 'Plan',
    status: 'Statut',
    students: 'Élèves',
    users: 'Utilisateurs',
    revenue: 'Revenu mensuel',
    renewal: 'Renouvellement',
    createdAt: 'Inscription',
    lastAccess: 'Dernier accès',
    close: 'Fermer',
  },
  editModal: {
    title: "Modifier l'école",
    name: "Nom de l'école",
    shortName: 'Nom abrégé',
    country: 'Pays',
    city: 'Ville',
    phone: 'Téléphone',
    officialEmail: 'Email officiel',
    officialCode: 'Code officiel',
    cancel: 'Annuler',
    save: 'Enregistrer',
    saving: 'Enregistrement…',
    saved: 'École mise à jour.',
  },
  suspendModal: {
    titleSuspend: "Suspendre l'école",
    titleReactivate: "Réactiver l'école",
    bodySuspend: (name: string) =>
      `L'abonnement de « ${name} » sera suspendu — l'école apparaîtra comme Suspendu et ne sera plus facturée.`,
    bodyReactivate: (name: string) => `L'abonnement de « ${name} » sera réactivé.`,
    noSubscription: 'Cette école n’a pas d’abonnement — rien à suspendre.',
    confirmSuspend: 'Suspendre',
    confirmReactivate: 'Réactiver',
    cancel: 'Annuler',
    doneSuspend: 'Abonnement suspendu.',
    doneReactivate: 'Abonnement réactivé.',
  },
  deleteModal: {
    title: "Supprimer l'école",
    warning: (name: string) =>
      `Action irréversible : « ${name} », ses classes, élèves, notes, bulletins et paiements seront définitivement supprimés. Le compte du propriétaire est conservé.`,
    confirmLabel: (name: string) => `Tape « ${name} » pour confirmer`,
    confirm: 'Supprimer définitivement',
    cancel: 'Annuler',
    done: 'École supprimée.',
    mismatch: "Le nom saisi ne correspond pas à l'école.",
    superadminOnly: 'Seul un SUPERADMIN peut supprimer une école.',
  },
  pagerLabel: 'écoles',
  empty: 'Aucune école ne correspond aux filtres.',
  emptyNoSchools: 'Aucune école enregistrée pour le moment.',
  loadError: 'Impossible de charger les écoles.',
  retry: 'Réessayer',
  stub: 'Cette fonctionnalité arrive bientôt.',
} as const;

export const ADMIN_USERS = {
  title: 'Utilisateurs',
  subtitle: 'Gestion de tous les comptes utilisateurs à travers les écoles clientes',
  exportCsv: 'Exporter',
  kpi: {
    totalUsers: 'Utilisateurs totaux',
    thisMonth: (n: number) => `+${n} ce mois`,
    activeUsers: 'Utilisateurs actifs',
    activePct: (p: number) => `${p}% actifs`,
    schoolAdmins: "Admins d'école",
    schoolAdminsSub: 'Propriétaires et admins',
    suspended: 'Comptes suspendus',
  },
  filters: {
    searchPlaceholder: 'Rechercher un utilisateur...',
    allSchools: 'Toutes les écoles',
    allRoles: 'Tous les rôles',
    allStatuses: 'Tous les statuts',
    reset: 'Réinitialiser',
    results: (n: number) => `${n} utilisateur${n > 1 ? 's' : ''} trouvé${n > 1 ? 's' : ''}`,
  },
  list: {
    title: 'Liste des utilisateurs',
    subtitle: 'Tous les comptes actifs et inactifs sur la plateforme',
    tabs: { all: 'Tous', active: 'Actifs', suspended: 'Suspendus' },
  },
  columns: {
    user: 'Utilisateur',
    school: 'École',
    role: 'Rôle',
    status: 'Statut',
    lastLogin: 'Dernière connexion',
    createdAt: 'Inscrit le',
    actions: 'Actions',
  },
  actions: {
    viewProfile: 'Voir le profil',
    edit: 'Modifier',
    resetPassword: 'Réinitialiser le mot de passe',
    impersonate: 'Se connecter en tant que...',
    suspend: 'Suspendre le compte',
    reactivate: 'Réactiver le compte',
    delete: 'Supprimer',
  },
  profileModal: {
    title: 'Profil utilisateur',
    email: 'Email',
    school: 'École',
    orgRole: 'Rôle',
    appRole: 'Rôle plateforme',
    status: 'Statut',
    emailVerified: 'Email vérifié',
    lastLogin: 'Dernière connexion',
    createdAt: 'Inscrit le',
    yes: 'Oui',
    no: 'Non',
    close: 'Fermer',
  },
  suspendModal: {
    titleSuspend: 'Suspendre le compte',
    titleReactivate: 'Réactiver le compte',
    bodySuspend: (name: string) =>
      `« ${name} » ne pourra plus se connecter tant que le compte est suspendu.`,
    bodyReactivate: (name: string) => `« ${name} » pourra de nouveau se connecter.`,
    superadminOnly: 'Seul un SUPERADMIN peut réactiver un compte suspendu.',
    confirmSuspend: 'Suspendre',
    confirmReactivate: 'Réactiver',
    cancel: 'Annuler',
    doneSuspend: 'Compte suspendu.',
    doneReactivate: 'Compte réactivé.',
  },
  pagerLabel: 'utilisateurs',
  empty: 'Aucun utilisateur ne correspond aux filtres.',
  loadError: 'Impossible de charger les utilisateurs.',
  retry: 'Réessayer',
  stub: 'Cette fonctionnalité arrive bientôt.',
} as const;

export const ADMIN_STATS = {
  title: 'Statistiques de la plateforme',
  subtitle: "Analyse détaillée de la croissance, de l'usage et des revenus",
  export: 'Exporter',
  periods: [
    { key: '7d', label: '7 jours' },
    { key: '30d', label: '30 jours' },
    { key: '6m', label: '6 mois' },
    { key: '12m', label: '1 an' },
  ],
  kpi: {
    totalSchools: 'Total écoles',
    totalStudents: 'Total élèves',
    retention: 'Taux de rétention',
    retentionSub: 'Comptes actifs sur 30 j.',
    arr: 'Revenu annuel (ARR)',
    arrSub: 'MRR actif × 12',
    revPerStudent: 'Rev. par élève/mois',
    revPerStudentSub: 'Moyenne facturée',
    thisMonth: 'ce mois',
    notEnoughData: 'Données insuffisantes',
  },
  revenue: {
    title: 'Évolution des revenus',
    subtitle: 'Facturation par élève — période sélectionnée',
    total: 'Total période',
    avg: 'Moyenne',
    peak: 'Pic de revenu',
    yoy: 'Croissance YoY',
  },
  plans: {
    title: 'Répartition des plans',
    subtitle: (n: number) => `${n} abonnement${n > 1 ? 's' : ''} actif${n > 1 ? 's' : ''}`,
    center: 'écoles',
    expired: (n: number) => `Expirés — ${n} école${n > 1 ? 's' : ''}`,
    empty: 'Aucun abonnement actif pour le moment.',
  },
  growth: {
    title: 'Métriques de croissance',
    subtitle: 'Indicateurs clés de performance',
    newSchools: 'Nouvelles écoles',
    newSchoolsSub: 'Inscriptions ce mois',
    newStudents: 'Nouveaux élèves enregistrés',
    newStudentsSub: 'Cumulé sur le mois',
    grades: 'Notes saisies',
    gradesSub: 'Toutes écoles, ce mois',
    appreciations: 'Appréciations rédigées',
    appreciationsSub: 'Toutes écoles, ce mois',
    churn: 'Taux de désabonnement',
    churnSub: 'Churn mensuel',
    ltv: 'Valeur vie client (LTV)',
    ltvSub: 'Estimation moyenne',
  },
  geo: {
    title: 'Répartition géographique',
    subtitle: 'Écoles par pays',
    schools: (n: number) => `${n} école${n > 1 ? 's' : ''}`,
    empty: 'Aucune école enregistrée.',
  },
  heatmap: {
    title: 'Activité hebdomadaire',
    subtitle: 'Connexions par jour et créneau — 30 derniers jours',
    low: 'Faible',
    high: 'Élevé',
    empty: 'Aucune connexion enregistrée sur la période.',
  },
  loadError: 'Impossible de charger les statistiques.',
  retry: 'Réessayer',
} as const;

export const ADMIN_SUBSCRIPTIONS = {
  title: 'Abonnements',
  subtitle: 'Gestion des abonnements actifs, suspendus et expirés de toutes les écoles clientes',
  export: 'Exporter',
  newSubscription: 'Nouvel abonnement',
  kpi: {
    active: 'Abonnements actifs',
    activeSub: (n: number) => `+${n} ce mois-ci`,
    mrr: 'Revenus mensuels (MRR)',
    vsLastMonth: 'vs mois dernier',
    renewals: 'Renouvellements ce mois',
    nextRenewal: (d: string) => `Prochaine : ${d}`,
    expired: 'Abonnements expirés',
    actionRequired: 'Action requise',
  },
  planBreakdown: {
    title: 'Répartition par plan',
    center: 'écoles',
    expired: (n: number) => `Expirés — ${n} école${n > 1 ? 's' : ''}`,
    empty: 'Aucun abonnement actif.',
  },
  mrrChart: { title: 'Revenus des 6 derniers mois', thisMonth: 'Ce mois', growth: 'Croissance' },
  filters: {
    searchPlaceholder: 'Rechercher une école...',
    allPlans: 'Tous les plans',
    allStatuses: 'Tous les statuts',
  },
  list: {
    title: 'Tous les abonnements',
    subtitle: (total: number, active: number) =>
      `${total} abonnement${total > 1 ? 's' : ''} au total · ${active} actif${active > 1 ? 's' : ''}`,
  },
  columns: {
    school: 'École',
    plan: 'Plan',
    students: 'Élèves',
    rate: 'Tarif / mois',
    amount: 'Montant',
    renewal: 'Renouvellement',
    status: 'Statut',
    actions: 'Actions',
  },
  perStudent: '/ élève',
  inDays: (n: number) => `dans ${n} jour${n > 1 ? 's' : ''}`,
  sinceDays: (n: number) => `Depuis ${n} jour${n > 1 ? 's' : ''}`,
  manage: 'Gérer',
  relaunch: 'Relancer',
  alert: {
    title: (n: number) =>
      `${n} abonnement${n > 1 ? 's' : ''} arrive${n > 1 ? 'nt' : ''} à échéance dans les 30 prochains jours`,
    body: (names: string, more: number) =>
      more > 0
        ? `${names} et ${more} autre${more > 1 ? 's' : ''} — Envoyez des rappels de renouvellement.`
        : `${names} — Envoyez des rappels de renouvellement.`,
    sendReminders: 'Envoyer rappels',
  },
  createModal: {
    title: 'Nouvel abonnement',
    school: 'École',
    schoolPlaceholder: 'Choisir une école sans abonnement',
    noFreeSchool: 'Toutes les écoles ont déjà un abonnement.',
    plan: 'Plan',
    status: 'Statut initial',
    trial: 'Essai',
    activeNow: 'Actif',
    renewsAt: 'Date de renouvellement',
    trialEndsAt: "Fin de l'essai",
    couponCode: 'Code coupon (optionnel)',
    cancel: 'Annuler',
    create: "Créer l'abonnement",
    creating: 'Création…',
    created: 'Abonnement créé.',
  },
  manageModal: {
    title: "Gérer l'abonnement",
    plan: 'Plan',
    status: 'Statut',
    renewsAt: 'Date de renouvellement',
    couponCode: 'Code coupon',
    couponHint: 'Vider le champ pour détacher le coupon',
    cancel: 'Annuler',
    save: 'Enregistrer',
    saving: 'Enregistrement…',
    saved: 'Abonnement mis à jour.',
  },
  pagerLabel: 'abonnements',
  empty: 'Aucun abonnement — créez le premier.',
  loadError: 'Impossible de charger les abonnements.',
  retry: 'Réessayer',
  stub: 'Cette fonctionnalité arrive bientôt.',
} as const;

export const ADMIN_TRANSACTIONS = {
  title: 'Transactions',
  subtitle: 'Historique complet des paiements et revenus générés sur la plateforme',
  exportCsv: 'Exporter CSV',
  reportPdf: 'Rapport PDF',
  recordPayment: 'Enregistrer un paiement',
  kpi: {
    year: (y: number) => `Revenus totaux (${y})`,
    vsPrevYear: (y: number) => `vs ${y}`,
    month: 'Revenus ce mois (MRR)',
    vsLastMonth: 'vs mois dernier',
    monthCount: 'Transactions ce mois',
    pendingRefunds: 'Paiements en attente',
    toProcess: 'à traiter',
  },
  chart: {
    title: (y: number) => `Revenus mensuels ${y}`,
    best: 'Meilleur mois',
    ytd: 'Cumul 12 mois',
  },
  methods: {
    title: 'Répartition des paiements',
    labels: { STRIPE: 'Stripe', MANUAL: 'Manuel', BANK_TRANSFER: 'Virement bancaire' } as Record<
      string,
      string
    >,
    succeeded: 'Transactions réussies',
    failed: 'Transactions échouées',
    refunded: 'Remboursements',
    refundedSub: (v: string) => `${v} remboursés`,
    avgTicket: 'Ticket moyen',
    perTx: '/ transaction',
  },
  filters: {
    searchPlaceholder: 'Rechercher une école, réf. transaction...',
    allMonths: 'Tous les mois',
    allStatuses: 'Tous les statuts',
    allMethods: 'Tous les moyens',
  },
  list: {
    title: 'Historique des transactions',
    subtitle: (n: number) => `${n} transaction${n > 1 ? 's' : ''} au total`,
  },
  columns: {
    reference: 'ID Transaction',
    school: 'École',
    plan: 'Plan',
    amount: 'Montant',
    method: 'Moyen de paiement',
    date: 'Date',
    period: 'Période couverte',
    status: 'Statut',
    actions: 'Actions',
  },
  view: 'Voir',
  detailModal: {
    title: 'Détail de la transaction',
    reference: 'Référence',
    school: 'École',
    amount: 'Montant',
    method: 'Moyen',
    date: 'Date',
    period: 'Période couverte',
    status: 'Statut',
    refundedBy: 'Remboursée par',
    refundOf: 'Remboursement de',
    refund: 'Rembourser',
    refunding: 'Remboursement…',
    refunded: 'Remboursement enregistré.',
    close: 'Fermer',
  },
  recordModal: {
    title: 'Enregistrer un paiement',
    school: 'École',
    schoolPlaceholder: 'Choisir une école abonnée',
    amount: 'Montant (USD)',
    amountHint: 'Ex : 156.00',
    method: 'Moyen de paiement',
    status: 'Statut',
    period: 'Période couverte (mois)',
    cancel: 'Annuler',
    save: 'Enregistrer',
    saving: 'Enregistrement…',
    saved: 'Paiement enregistré.',
    invalidAmount: 'Montant invalide.',
  },
  pagerLabel: 'transactions',
  empty: 'Aucune transaction — les paiements enregistrés apparaîtront ici.',
  loadError: 'Impossible de charger les transactions.',
  retry: 'Réessayer',
  stub: 'Cette fonctionnalité arrive bientôt.',
} as const;

export const ADMIN_COUPONS = {
  title: 'Coupons & Codes Promo',
  subtitle: 'Créez et gérez des codes promotionnels pour les abonnements des écoles clientes',
  export: 'Exporter',
  createCoupon: 'Créer un coupon',
  kpi: {
    active: 'Coupons actifs',
    totalUses: 'Utilisations totales',
    monthlyDiscount: 'Remises en cours / mois',
    monthlyDiscountSub: 'Sur les abonnements actifs',
    expired: 'Coupons expirés',
    expiredSub: 'Non renouvelés',
  },
  filters: {
    searchPlaceholder: 'Rechercher un coupon...',
    allTypes: 'Tous les types',
    allPlans: 'Tous les plans',
  },
  typeLabels: {
    PERCENT: '% Pourcentage',
    FIXED: '$ Fixe',
    FREE_MONTH: '🎁 Mois offert',
  } as Record<string, string>,
  list: {
    title: 'Liste des coupons',
    subtitle: (total: number, active: number, expired: number) =>
      `${total} coupon${total > 1 ? 's' : ''} au total · ${active} actif${active > 1 ? 's' : ''} · ${expired} expiré${expired > 1 ? 's' : ''}`,
  },
  columns: {
    code: 'Code',
    type: 'Type',
    discount: 'Remise',
    plan: 'Plan',
    uses: 'Utilisations',
    limit: 'Limite',
    expiry: 'Expiration',
    status: 'Statut',
    stripe: 'Checkout Stripe',
    actions: 'Actions',
  },
  // Whether the code can be typed on the hosted Stripe Checkout page. The
  // back-office mirrors each coupon as a Stripe Promotion Code (same code).
  stripe: {
    synced: 'Saisissable',
    syncedHint: 'Le code peut être saisi sur la page de paiement Stripe.',
    pending: 'À synchroniser',
    pendingHint:
      'Pas encore sur Stripe — le code ne sera pas accepté sur la page de paiement. Utilisez « Synchroniser avec Stripe ».',
    notRedeemable: 'Hors Stripe',
    notRedeemableHint:
      'Seul le plan Établissement Pro est facturé via Stripe : ce coupon ne s’applique pas sur la page de paiement.',
    notConfigured: 'Stripe inactif',
    notConfiguredHint: 'Stripe n’est pas configuré sur cet environnement.',
    syncAction: 'Synchroniser avec Stripe',
    syncDone: 'Coupon synchronisé avec Stripe.',
    createdUnsynced:
      'Coupon créé, mais pas encore sur Stripe — utilisez « Synchroniser avec Stripe » pour le rendre saisissable.',
  },
  allPlans: 'Tous les plans',
  perMonths: (n: number) => `/ ${n} mois`,
  permanent: 'permanent',
  free: 'gratuit',
  maxUses: (n: number) => `${n} max.`,
  unlimited: 'Illimité',
  noExpiry: '—',
  expiredOn: (d: string) => `Expiré le ${d}`,
  actions: {
    edit: 'Modifier',
    duplicate: 'Dupliquer',
    disable: 'Désactiver',
    enable: 'Réactiver',
    delete: 'Supprimer',
  },
  formModal: {
    titleCreate: 'Nouveau coupon',
    titleEdit: 'Modifier le coupon',
    subtitle: 'Configurez les paramètres du code promotionnel',
    typeLabel: 'Type de remise',
    types: {
      PERCENT: { label: 'Pourcentage', example: 'Ex : 20% de réduction' },
      FIXED: { label: 'Montant fixe', example: 'Ex : -$50 sur le plan' },
      FREE_MONTH: { label: 'Mois offert', example: 'Ex : 1 mois gratuit' },
    },
    code: 'Code promotionnel',
    codeHint: 'Généré automatiquement ou saisi manuellement',
    generate: 'Générer',
    valuePercent: 'Valeur de la remise (%)',
    valueFixed: 'Montant de la remise (USD)',
    valueFreeMonths: 'Nombre de mois offerts',
    duration: 'Durée (mois)',
    durationHint: 'Laisser vide pour une remise permanente',
    plan: 'Plan applicable',
    maxUses: "Limite d'utilisation",
    maxUsesHint: 'Laisser vide pour illimité',
    expiresAt: "Date d'expiration",
    description: 'Description interne',
    cancel: 'Annuler',
    save: 'Enregistrer le coupon',
    saving: 'Enregistrement…',
    created: 'Coupon créé.',
    updated: 'Coupon mis à jour.',
    codeTaken: 'Ce code existe déjà.',
  },
  deleteModal: {
    title: 'Supprimer le coupon',
    body: (code: string) => `Le coupon « ${code} » sera définitivement supprimé.`,
    inUse: 'Ce coupon est attaché à des abonnements — désactivez-le plutôt.',
    confirm: 'Supprimer',
    cancel: 'Annuler',
    done: 'Coupon supprimé.',
  },
  toggled: { disabled: 'Coupon désactivé.', enabled: 'Coupon réactivé.' },
  copied: 'Code copié.',
  pagerLabel: 'coupons',
  empty: 'Aucun coupon — créez votre premier code promo.',
  loadError: 'Impossible de charger les coupons.',
  retry: 'Réessayer',
} as const;

export const ADMIN_SETTINGS = {
  title: 'Paramètres Système',
  subtitle: 'Configuration globale de la plateforme',
  discard: 'Réinitialiser',
  save: 'Enregistrer les modifications',
  saving: 'Enregistrement…',
  saved: 'Paramètres enregistrés.',
  superadminOnly: 'Lecture seule — les modifications sont réservées au SUPERADMIN.',
  nav: {
    general: 'Général',
    billing: 'Plans & Tarification',
    notifications: 'Notifications & Alertes',
    security: 'Sécurité & Accès',
    backups: 'Sauvegardes & Données',
    danger: 'Zone de danger',
  },
  general: {
    title: 'Identité de la plateforme',
    description: 'Nom, domaine et informations de contact affichés aux écoles clientes',
    platformName: 'Nom de la plateforme',
    domain: 'Domaine principal',
    supportEmail: 'Email de support',
    timezone: 'Fuseau horaire',
    locale: 'Langue par défaut',
    locales: { fr: 'Français', en: 'English' } as Record<string, string>,
    logo: 'Logo de la plateforme',
    logoHint: 'PNG, JPG ou WebP — affiché dans les entêtes et emails',
    version: 'Version de la plateforme',
  },
  billing: {
    title: 'Plans & Tarification',
    description: 'Tarifs par élève et période d’essai appliqués aux nouveaux abonnements',
    currency: 'Devise',
    currencyValue: 'USD — Dollar américain',
    pricePerStudent: (plan: string) => `Tarif ${plan} (par élève / mois)`,
    trialDays: "Période d'essai (jours)",
    trialDaysHint: 'Appliquée aux nouveaux abonnements en statut Essai',
    stripeTitle: 'Passerelle de paiement Stripe',
    stripeConnected: 'Connecté',
    stripeNotConfigured: 'Non configuré',
    stripePartial: (missing: string[]) => `Incomplet — manque ${missing.join(', ')}`,
    stripeMode: { live: 'Mode production', test: 'Mode test' } as Record<string, string>,
    stripeHint:
      'État lu depuis la configuration serveur (STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, STRIPE_PRICE_ID_PRO) — les valeurs ne sont jamais affichées.',
  },
  notifications: {
    title: 'Notifications & Alertes',
    description: 'Alertes envoyées à l’équipe plateforme',
    channelPending: "Prendra effet à l'activation du canal d'envoi.",
    items: {
      notifyNewSubscription: {
        label: 'Nouvel abonnement',
        sub: 'Alerte quand une école souscrit un abonnement',
      },
      notifyFailedPayment: {
        label: 'Paiement échoué',
        sub: 'Alerte quand un paiement est refusé ou échoue',
      },
      weeklyReport: {
        label: 'Rapport hebdomadaire',
        sub: 'Résumé des métriques clés chaque lundi',
      },
      expiryReminders: {
        label: 'Expirations à J-7',
        sub: 'Alerte 7 jours avant l’échéance d’un abonnement',
      },
    },
  },
  security: {
    title: 'Sécurité & Accès',
    description: 'Paramètres de session et d’accès à l’administration',
    primaryAdmin: 'Administrateur principal',
    sessionTitle: 'Durée de session',
    sessionValue: 'Jeton d’accès 15 min · renouvellement 7 jours',
    sessionHint: 'Piloté par le cœur d’authentification — non modifiable ici',
    twoFa: 'Authentification à deux facteurs (2FA)',
    apiKey: 'Clé API publique',
    comingSoon: 'Bientôt disponible',
  },
  backups: {
    title: 'Sauvegardes & Données',
    description: 'Gestion des sauvegardes de la base de données',
    body: 'Les sauvegardes sont gérées automatiquement par l’hébergeur de la base de données (Neon) — instantanés continus et restauration à un point dans le temps. Aucune action n’est requise ici.',
  },
  danger: {
    title: 'Zone de danger',
    resetTitle: 'Réinitialiser les paramètres',
    resetBody:
      'Tous les paramètres de la plateforme reviennent à leurs valeurs par défaut. Les tarifs des plans ne sont pas affectés.',
    resetButton: 'Réinitialiser',
    modalTitle: 'Réinitialiser les paramètres',
    modalBody: (word: string) => `Cette action est irréversible. Tapez « ${word} » pour confirmer.`,
    confirmWord: 'RESET',
    cancel: 'Annuler',
    confirm: 'Réinitialiser',
    resetting: 'Réinitialisation…',
    done: 'Paramètres réinitialisés.',
  },
  invalidPrice: 'Tarif invalide.',
  loadError: 'Impossible de charger les paramètres.',
  retry: 'Réessayer',
} as const;

// Paramètres › Apparence (école) + carte « Apparence » des Paramètres Système
// (admin SaaS) — même composant ThemePicker, préférence PAR UTILISATEUR.
export const APPEARANCE = {
  tab: 'Apparence',
  adminNav: 'Apparence',
  title: 'Thème de couleur',
  description:
    'Choisis la palette de l’application. Préférence personnelle : elle s’applique immédiatement, sur tous tes appareils, et ne change rien pour les autres membres.',
  groupLabel: 'Thème de couleur',
  current: 'Actuel',
  default: 'Par défaut',
  previewAlt: (label: string) => `Aperçu du thème ${label}`,
  applied: (label: string) => `Thème « ${label} » appliqué.`,
  saveError: 'Thème appliqué sur cet appareil, mais impossible de l’enregistrer sur ton compte.',
  contrastNote:
    'Toutes les palettes respectent le contraste WCAG AA (texte ≥ 4,5:1) — les couleurs d’état (succès, alerte, erreur) et des matières restent identiques.',
} as const;
